vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - eamodio.gitlens
    - GitHub.vscode-pull-request-github
    - llvm-vs-code-extensions.vscode-clangd
    - mads-hartmann.bash-ide-vscode
    - mhutchie.git-graph
    - ms-vscode.makefile-tools
    - timonwong.shellcheck
